### ISSUE TITLE
Ubuntu 16.04 환경에서 오류 발생

### ISSUE THREAD

**Issue by NamGungGeon** [brotherstone97/CPSP_OCRServer_DRF#7]
TypeError: join() argument must be str or bytes, not 'PosixPath'

**Comment by NamGungGeon** [comment]
Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    main()
  File "manage.py", line 24, in main
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/var/www/html/cyphers-supporter/img-uploader/CPSP_DRF/settings.py", line 129, in <module>
    SCREENSHOT_ROOT = os.path.join(BASE_DIR, 'images')
  File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'PosixPath'

**Comment by brotherstone97** [comment]
됐습니까?
